{% set name = "trollimage" %}
{% set version = "1.5.4" %}
{% set sha256 = "467c2f7ab2ea49ce911a0e2b39190481e7a6610908bcbfd897cf1e46e7f9c13b" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy >=1.6
    - pillow
    - six
    - xarray
    - dask
    - rasterio

test:
  imports:
    - trollimage

about:
  home: https://github.com/pytroll/trollimage
  license: GPLv3+
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Pytroll imaging library
  description: Pytroll imaging library
  doc_url: http://trollimage.readthedocs.io/
  dev_url: https://github.com/pytroll/trollimage

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - adybbroe
    - pnuu
