{% set name = "trollimage" %}
{% set version = "1.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e6c522c8f4545d5d4ffa685e0eccdc599c5d1b5f171d08eca3fb4f4742a65cf3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - numpy >=1.6
    - pillow
    - six
    - xarray
    - dask
    - rasterio

test:
  imports:
    - trollimage

about:
  home: https://github.com/pytroll/trollimage
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Pytroll imaging library
  description: Pytroll imaging library
  doc_url: http://trollimage.readthedocs.io/
  dev_url: https://github.com/pytroll/trollimage

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - adybbroe
    - pnuu
