{% set name = "trollimage" %}
{% set version = "1.26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4ea98c7eb6ef48d7c8c03dbc874fec4071972d4036e5f2a751ca6bc669be50d1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3                             # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pip
    - setuptools
    - versioneer
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - numpy
    - cython >=3
    - versioneer
  run:
    - python
    - numpy
    - pillow
    - xarray
    - dask
    - rasterio

test:
  imports:
    - trollimage

about:
  home: https://github.com/pytroll/trollimage
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Pytroll imaging library
  description: Pytroll imaging library
  doc_url: http://trollimage.readthedocs.io/
  dev_url: https://github.com/pytroll/trollimage

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - adybbroe
    - pnuu
