{% set name = "trollimage" %}
{% set version = "1.28.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 84d3764d9b4949db3bed1aee8b81d21e20a058c07986597d02ab38fd90be13ab

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<311]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3                             # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pip
    - setuptools
    - versioneer
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - numpy
    - cython >=3
    - versioneer
  run:
    - python
    - numpy
    - pillow
    - xarray
    - dask
    - rasterio

test:
  imports:
    - trollimage

about:
  home: https://github.com/pytroll/trollimage
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Pytroll imaging library
  description: Pytroll imaging library
  doc_url: http://trollimage.readthedocs.io/
  dev_url: https://github.com/pytroll/trollimage

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - adybbroe
    - pnuu
