travis:
  secure:
    BINSTAR_TOKEN: HqvgDdnTg79T+be75o/McmvB63KHLSGvyr1YYms045oP1uu+lY36DdqR6JoW2W0ONuiWvqIc6vt1zXKuyifmpIMYhpx08IvUxGhFnUxM5bmAgLsyo8yMXCyP9wodpXIZin+rNEI/nfNQEOaxLmXyhx2qoVFwPDYoXEyXjRUCXXRlc0j68a2aeBv2PA1/VBVCKPKhXZOvj8AZegYfrk6se2CjaX9llcu8+myx88mnR/SjZ/TjEdTY59nlv47z+9irhhX6wSMXgIcaJp/j008IfzKW6ez87EfO7W6L7eTprYujI9WuTtJSBrDCI2oeeN8svArXE4uhClbFmBghElBhSDpAN2QPNwGblq+xH+dp2zMzFC4BSoMWRTMBGA+xgF8nrgJVYHkzgdC+eRkAjpoSmVzf91SRsiPyCDO5G0o8zuGnhUAuyVRW/PXvUq4koJqFbQgfBWrJthRVml9enIf/vRosEWKfI2OTwy9SLwsINWoWG3R2gWdFDjcADdDjZHKvQoKudU3slEA2a5EmIUKm6yLV7ELxE7HgZd3W/OpW+uPpylnD7tghF/M/mcQIlSW+29kdhaHPyjNR4OaitzFOoComlsjUNDDlgxboYdpePNcRK3/WTkigCNeZdyi99Sft4NQ9rBE37LWrAshjBQKQ678Go+Pz9Nfr5+EzCOwPOIg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
