travis:
  secure:
    BINSTAR_TOKEN: yFxRBD3IJBfRvnIvcdDHoe6Pki9P1NYrM7H8XPcR3l6IBQCnw6Er5Nxi3G6qi0qguYLC64uklBldcKhfFMvm7vShIad/AGFUWUNPHZwgtH/PT1GRfV0SbXCOlbFD7bboaiF4HHsZLSZ2F68CcnxzfwFjOP+3s0urhbM1DDTySMurzUUIugm2t9C4N+mt9BFMmURqWP/UN1d6hB2PW5oKrNV7fSZwN1aYQNMmpRTS0TZ3zn6jA85a9HpOZkO8oGr1XJXGKoQMy21dgweJyfIhsNasjYsHfSKOVVAEFvxxhkwntFepqAZlILOu9DUprkLrJT/2uIuMMb9XR6Q2ICvjdW3cClPh1eWZnI46d9VglUVGpk3Sq0LAuZylQjZH3PoJqpX7ebQ2UqlvdsMAzJZPwCG4toymftas1qJbkoAM8HfBOtpi9+C0HlmIQYy6VkZlL5VLQoS0OQs0WGBKsIwokIMk/6CwWc3VGgLPLrsSEoaK8TGTN4iJ4u2xe4OY7kG3588vnfpg/JcBJn8jgQGNd79ge9ebD+rVwJLeM69fv7WFvtO6iGrmXRUUZqa1fbveI7dfmAed6IK76j2/KirICMo+OpqZhIFpxleqqaurS0JBzN67DNaJjDpJTwiK/P+mHYn7FtK/u0PUP32iJD4TQLnkE3xBYE3kFx70tNss+Vc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
